# Site wide configuration

title: My Heartstrings
locale: en_US
description: Thinking life with photos.
logo: site-logo.png
search: true
url: http://zazie.github.io/my-heartstrings
url: http://localhost:4000

# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: false
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..2
  use_coderay: false

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "vendor"]

comments: true

# Site owner
owner:
  name: Megumi M
  avatar: http://s.gravatar.com/avatar/8ffb43e2b6d32330a370fd47b83fecbd?s=200
  email: zazie.tokyo@gmail.com
  disqus-shortname:
  twitter: zazie
  facebook: zazie.tokyo
  github: zazie
  linkedin:
  instagram: zazie
  flickr: zazie-tyo
  tumblr: zazie-tyo
  pinterest: megutv
  google:
    plus:
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
